timeout: 1200s
steps:
  # terraform init -input=false
  - name: "hashicorp/terraform:0.12.29"
    args:
      - init
      - -input=false
  # terraform validate
  - name: "hashicorp/terraform:0.12.29"
    args:
      - validate
  # terraform plan -input=false -out=tfplan
  - name: "hashicorp/terraform:0.12.29"
    args:
      - plan
      - -input=false
      - -out=tfplan
