steps:
  - name: 'gcr.io/cloud-foundation-cicd/cft/developer-tools:$_DOCKER_TAG_VERSION_DEVELOPER_TOOLS'
    id: 'lint'
    args: ['/usr/local/bin/test_lint.sh']
tags:
  - 'ci'
  - 'lint'
substitutions:
  _DOCKER_IMAGE_DEVELOPER_TOOLS: 'cft/developer-tools'
  _DOCKER_TAG_VERSION_DEVELOPER_TOOLS: '0.12.2'
